---
captainVersion: 4
caproverOneClickApp:
    instructions:
        start: |
            unCoded Trading Bot - Bitte fuellen Sie alle erforderlichen Felder aus.

            Nach dem Deployment ist das Bot-Dashboard erreichbar unter:
            IHRE-SERVER-IP:4000
        end: |
            Deployment abgeschlossen! Ihre Trading Bot Anwendung ist aktiv.
            Bot-Dashboard: IHRE-SERVER-IP:$$cap_frontend_port
    displayName: unCoded Trading Bot
    description: Trading Bot mit Telegram Integration und PostgreSQL Datenbank
    documentation: Taken from https://uncoded-1.gitbook.io/uncoded-docs/
    isOfficial: true
    variables:
        - id: $$cap_postgres_password
          label: PostgreSQL Password
          description: Passwort fuer die PostgreSQL Datenbank
          defaultValue: $$cap_gen_random_hex(16)
          validRegex: /.{8,}/
        - id: $$cap_api_key
          label: Binance API Key
          description: Ihr Binance API Key
          defaultValue: ''
          validRegex: /.+/
        - id: $$cap_api_secret
          label: Binance API Secret
          description: Ihr Binance API Secret
          defaultValue: ''
          validRegex: /.+/
        - id: $$cap_telegram_bot_token
          label: Telegram Bot Token
          description: Telegram Bot Token von @BotFather
          defaultValue: ''
          validRegex: /.+/
        - id: $$cap_telegram_group_id
          label: Telegram Group ID
          description: Ihre Telegram Gruppen-ID
          defaultValue: ''
          validRegex: /.+/
        - id: $$cap_telegram_owner_id
          label: Telegram Owner ID
          description: Ihre persoenliche Telegram User-ID
          defaultValue: ''
          validRegex: /.+/
        - id: $$cap_frontend_port
          label: Frontend PORT
          description: Interner Port, auf dem das Frontend lauscht
          defaultValue: '4000'
          validRegex: /^\d+$/
        - id: $$cap_app_password
          label: APP Password
          description: Passwort fuer den App-Login
          defaultValue: ''
          validRegex: /.+/
services:
    $$cap_appname-db:
        image: postgres:16
        restart: always
        volumes:
            - $$cap_appname-db-data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: uncoded_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: $$cap_postgres_password
        caproverExtra:
            notExposeAsWebApp: true
    $$cap_appname-trading:
        image: aureumvictoria/uncoded-trading-bot:2025.09.09
        restart: always
        depends_on:
            - $$cap_appname-db
        environment:
            API_KEY: $$cap_api_key
            API_SECRET: $$cap_api_secret
            POSTGRES_HOST: srv-captain--$$cap_appname-db
            POSTGRES_PORT: 5432
            POSTGRES_DB: uncoded_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: $$cap_postgres_password
            DATABASE_URL: postgresql://postgres:$$cap_postgres_password@srv-captain--$$cap_appname-db:5432/uncoded_db
            PGSSLMODE: disable
        caproverExtra:
            notExposeAsWebApp: true
    $$cap_appname-telegram:
        image: aureumvictoria/uncoded-telegram-bot:2025.09.09
        restart: always
        depends_on:
            - $$cap_appname-db
            - $$cap_appname-trading
        environment:
            TELEGRAM_BOT_TOKEN: $$cap_telegram_bot_token
            TELEGRAM_GROUP_ID: $$cap_telegram_group_id
            TELEGRAM_OWNER_ID: $$cap_telegram_owner_id
            POSTGRES_HOST: srv-captain--$$cap_appname-db
            POSTGRES_PORT: 5432
            POSTGRES_DB: uncoded_db
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: $$cap_postgres_password
            DATABASE_URL: postgresql://postgres:$$cap_postgres_password@srv-captain--$$cap_appname-db:5432/uncoded_db
            PGSSLMODE: disable
        caproverExtra:
            notExposeAsWebApp: true
    $$cap_appname-frontend:
        image: tbotteam/uncoded-js-frontend:latest
        restart: always
        depends_on:
            - $$cap_appname-db
        ports:
            - '$$cap_frontend_port:$$cap_frontend_port'
        environment:
            POSTGRES_URL: postgresql://postgres:$$cap_postgres_password@srv-captain--$$cap_appname-db:5432/uncoded_db
            PORT: $$cap_frontend_port
            APP_PASSWORD: $$cap_app_password
        caproverExtra:
            containerHttpPort: $$cap_frontend_port
