name: Publish Pages

on:
  push:
    branches: [ master ]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        run: npm ci

      - name: Validate apps
        run: npm run validate_apps

      - name: Build dist
        run: npm run build

      - name: Publish to gh-pages
        env:
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./scripts/publish-from-actions.sh

